// Shared context
export const INVALIDATE_SHARED_CONTEXT = "INVALIDATE_SHARED_CONTEXT";
export const LOAD_SHARED_CONTEXT = "LOAD_SHARED_CONTEXT";
export const LOAD_SHARED_CONTEXT_SUCCESS = "LOAD_SHARED_CONTEXT_SUCCESS";
export const LOAD_SHARED_CONTEXT_FAILURE = "LOAD_SHARED_CONTEXT_FAILURE";