// Shared context
export const INVALIDATE_SHARED_CONTEXT = "INVALIDATE_SHARED_CONTEXT";
export const LOAD_SHARED_CONTEXT = "LOAD_SHARED_CONTEXT";
export const LOAD_SHARED_CONTEXT_SUCCESS = "LOAD_SHARED_CONTEXT_SUCCESS";
export const LOAD_SHARED_CONTEXT_FAILURE = "LOAD_SHARED_CONTEXT_FAILURE";
export const UPDATE_SHARED_CONTEXT_TITLE = "UPDATE_SHARED_CONTEXT_TITLE";

// Login
export const INVALIDATE_SEND_AUTHENTICATION_TOKEN = "INVALIDATE_AUTHENTICATION_TOKEN_REQUEST";
export const SEND_AUTHENTICATION_TOKEN = "REQUEST_AUTHENTICATION_TOKEN";
export const SEND_AUTHENTICATION_TOKEN_SUCCESS = "REQUEST_AUTHENTICATION_TOKEN_SUCCESS";
export const SEND_AUTHENTICATION_TOKEN_FAILURE = "REQUEST_AUTHENTICATION_TOKEN_FAILURE";

// Authenticator
export const AUTHENTICATE = "AUTHENTICATE";
export const AUTHENTICATE_SUCCESS = "AUTHENTICATE_SUCCESS";
export const AUTHENTICATE_FAILURE = "AUTHENTICATE_FAILURE";

// Account (Personal)
export const INVALIDATE_PERSONAL_ACCOUNT = "INVALIDATE_PERSONAL_ACCOUNT";
export const LOAD_PERSONAL_ACCOUNT = "LOAD_PERSONAL_ACCOUNT";
export const LOAD_PERSONAL_ACCOUNT_SUCCESS = "LOAD_PERSONAL_ACCOUNT_SUCCESS";
export const LOAD_PERSONAL_ACCOUNT_FAILURE = "LOAD_PERSONAL_ACCOUNT_FAILURE";

// Account
export const INVALIDATE_ACCOUNT = "INVALIDATE_ACCOUNT";
export const LOAD_ACCOUNT = "LOAD_ACCOUNT";
export const LOAD_ACCOUNT_SUCCESS = "LOAD_ACCOUNT_SUCCESS";
export const LOAD_ACCOUNT_FAILURE = "LOAD_ACCOUNT_FAILURE";