// Shared context
export const INVALIDATE_SHARED_CONTEXT = "INVALIDATE_SHARED_CONTEXT";
export const LOAD_SHARED_CONTEXT = "LOAD_SHARED_CONTEXT";
export const LOAD_SHARED_CONTEXT_SUCCESS = "LOAD_SHARED_CONTEXT_SUCCESS";
export const LOAD_SHARED_CONTEXT_FAILURE = "LOAD_SHARED_CONTEXT_FAILURE";
export const UPDATE_SHARED_CONTEXT_TITLE = "UPDATE_SHARED_CONTEXT_TITLE";

// Authentication
export const REQUEST_AUTHENTICATION_TOKEN = "REQUEST_AUTHENTICATION_TOKEN";
export const REQUEST_AUTHENTICATION_TOKEN_SUCCESS = "REQUEST_AUTHENTICATION_TOKEN_SUCCESS";
export const REQUEST_AUTHENTICATION_TOKEN_FAILURE = "REQUEST_AUTHENTICATION_TOKEN_FAILURE";
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

// Account
export const LOAD_ACCOUNT_DETAILS = "LOAD_ACCOUNT_DETAILS";
export const LOAD_ACCOUNT_DETAILS_SUCCESS = "LOAD_ACCOUNT_DETAILS_SUCCESS";
export const LOAD_ACCOUNT_DETAILS_FAILURE = "LOAD_ACCOUNT_DETAILS_FAILURE";
export const UPDATE_ACCOUNT_DISPLAY_NAME = "UPDATE_ACCOUNT_DISPLAY_NAME";
export const UPDATE_ACCOUNT_DISPLAY_NAME_SUCCESS = "UPDATE_ACCOUNT_DISPLAY_NAME_SUCCESS";
export const UPDATE_ACCOUNT_DISPLAY_NAME_FAILURE = "UPDATE_ACCOUNT_DISPLAY_NAME_FAILURE";

// Error
export const INVALIDATE_ERROR = "INVALIDATE_ERROR";
export const SET_ERROR = "SET_ERROR";

// Countdown
export const CREATE_COUNTDOWN = "CREATE_COUNTDOWN";
export const CREATE_COUNTDOWN_SUCCESS = "CREATE_COUNTDOWN_SUCCESS";
export const CREATE_COUNTDOWN_FAILURE = "CREATE_COUNTDOWN_FAILURE";
export const LOAD_COUNTDOWN = "LOAD_COUNTDOWN";
export const LOAD_COUNTDOWN_SUCCESS = "LOAD_COUNTDOWN_SUCCESS";
export const LOAD_COUNTDOWN_FAILURE = "LOAD_COUNTDOWN_FAILURE";